### ISSUE TITLE
Sipi's mimetype_consistency fails with .bin file

### ISSUE THREAD

**Issue by benjamingeer** [dasch-swiss/knora-api#1531]
Knora API v1 creates files with a `.bin` suffix using `FileUtil.createTempFile`. When such a file is submitted to Sipi using Knora's `convert_from_path.lua` script, the Sipi function `mimetype_consistency` fails with this error:

```
Sipi image error at [/sipi/src/SipiImage.cpp: 255]:
Unsupported file type: "tmp_7340135413634979849.bin
```

This seems to be why call to `mimetype_consistency` was commented out in `convert_from_path.lua` in PR #1459:

https://github.com/dasch-swiss/knora-api/pull/1459/files#diff-4a1a2aedd2d8b7dee2f824e33b243ca1R123

**Comment by benjamingeer** [comment]
It would also be better if Sipi had a function like `mimetype_consistency` that also worked with non-image files.

**Comment by tobiasschweizer** [comment]
see https://github.com/dasch-swiss/sipi/issues/316

**Comment by subotic** [comment]
> This seems to be why call to mimetype_consistency was commented out in convert_from_path.lua 

yes

**Comment by tobiasschweizer** [comment]
I think the problem is simply that the filename generated by Knora is submitted as the original filename:

https://github.com/dasch-swiss/knora-api/blob/4204ff7ff98934b8cb723f212ee5ea2d9de4fe0f/webapi/src/it/scala/org/knora/webapi/e2e/v1/KnoraSipiScriptsV1ITSpec.scala#L193

Changing it to the actually given filename "Chlaus.jpg" solves the problem for me. This was changed in https://github.com/dasch-swiss/knora-api/pull/1459/files#diff-c0e2fd38cb951767ceedc140eab63e10L203
