### ISSUE TITLE
V2 Resource creation optional creation date

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api#1542]
Why is the client allowed to submit a custom creation date when creation a resource? Wouldn't it be better if the system controlled this? 

A user could create a non-original annotation that "predates" and original contribution.  

Likewise: should the actual creator of a resource not automatically be the owner (unless ownership is transferred)?

**Comment by mrivoal** [comment]
I guess this could have something to do with the migration of data in Knora from an external database. I think we used it (and maybe even ask for it) for Lumières.Lausanne. Right, @gfoo ?

In this case, you might not want the history of the data creation to be erased as data is transfered to Knora.

> A user could create a non-original annotation that "predates" and original contribution.

But would this annotation be displayed by the GUI? Because the actual users of the old database would want this information to be displayed. They are not interested in seing the date of the data transfer in Knora.

**Comment by benjamingeer** [comment]
This was done in #1151 in response to @gfoo‘s requests in #1088 and #1089.

**Comment by gfoo** [comment]
>  I think we used it (and maybe even ask for it) for Lumières.Lausanne. Right, @gfoo ?

yep

**Comment by tobiasschweizer** [comment]
Ok, thanks for the explanation.
